---
- include_tasks:                'tasks/common/template_files.yml'
- include_tasks:                'tasks/common/scripts.yml'
  vars:
    scripts:
      - script:                 scripts/remove_module.sh "{{ module }}"
        changed_when:           False
  with_items:                   "{{ remove_modules }}"
  loop_control:
    loop_var:                   'module'
  when:                         template_files_result.changed
- include_tasks:                'tasks/test.yml'
  when:                         template_files_result.changed
